//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.19080
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSimpleMusicSite_CourseProject.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NamesAtrRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamesAtrRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcSimpleMusicSite_CourseProject.Resources.Models.NamesAtrRes", typeof(NamesAtrRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __________________________________________________________________________________________________.
        /// </summary>
        public static string _________________MusicEntities______________________ {
            get {
                return ResourceManager.GetString("_________________MusicEntities______________________", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлено.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото альбома.
        /// </summary>
        public static string AlbumPhoto {
            get {
                return ResourceManager.GetString("AlbumPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбомы исполнителя.
        /// </summary>
        public static string AlbumsOfTheArtist {
            get {
                return ResourceManager.GetString("AlbumsOfTheArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбомы данного жанра.
        /// </summary>
        public static string AlbumsOfTheGenre {
            get {
                return ResourceManager.GetString("AlbumsOfTheGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбом.
        /// </summary>
        public static string AlbumTitle {
            get {
                return ResourceManager.GetString("AlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год .
        /// </summary>
        public static string AlbumYear {
            get {
                return ResourceManager.GetString("AlbumYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель.
        /// </summary>
        public static string ArtistTile {
            get {
                return ResourceManager.GetString("ArtistTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость потока(Кб/c).
        /// </summary>
        public static string Bitrate {
            get {
                return ResourceManager.GetString("Bitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пароль.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание жанра.
        /// </summary>
        public static string DescriptionGenre {
            get {
                return ResourceManager.GetString("DescriptionGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачиваний.
        /// </summary>
        public static string Dowloads {
            get {
                return ResourceManager.GetString("Dowloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр.
        /// </summary>
        public static string GenreTitle {
            get {
                return ResourceManager.GetString("GenreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лайки.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прослушиваний.
        /// </summary>
        public static string Listened {
            get {
                return ResourceManager.GetString("Listened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к файлу.
        /// </summary>
        public static string PathToFile {
            get {
                return ResourceManager.GetString("PathToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прослушиваний за период.
        /// </summary>
        public static string PeriodPlays {
            get {
                return ResourceManager.GetString("PeriodPlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер(Мб).
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжительность(мин/сек).
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего прослушиваний.
        /// </summary>
        public static string TotalPlays {
            get {
                return ResourceManager.GetString("TotalPlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки данного жанра.
        /// </summary>
        public static string TrackOfTheGenre {
            get {
                return ResourceManager.GetString("TrackOfTheGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Композиции исполнителя.
        /// </summary>
        public static string TracksOfTheArtist {
            get {
                return ResourceManager.GetString("TracksOfTheArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название трека.
        /// </summary>
        public static string TrackTitle {
            get {
                return ResourceManager.GetString("TrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачал трек(и).
        /// </summary>
        public static string UserDowloadsTracks {
            get {
                return ResourceManager.GetString("UserDowloadsTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прослушал трек(и).
        /// </summary>
        public static string UserListenedTracks {
            get {
                return ResourceManager.GetString("UserListenedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставил лайк(и).
        /// </summary>
        public static string UserPutLikesTracks {
            get {
                return ResourceManager.GetString("UserPutLikesTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эл. почта.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string YourLogin {
            get {
                return ResourceManager.GetString("YourLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string YourPassword {
            get {
                return ResourceManager.GetString("YourPassword", resourceCulture);
            }
        }
    }
}
